### PR TITLE
Add exactWidth,exactHeight

### PR DESCRIPTION
**Pull request by iffy**
Sometimes I want to make something exactly a size.

Are you welcome to pull requests, btw?  I'm also interested in submitting a PR for two more functions:

```
matchBiggestWidth(objectToScale:Resizable, targets:Array<Resizable>, ...)
matchBiggestHeight(objectToScale:Resizable, targets:Array<Resizable>, ...)
```

### CODE REVIEW

**Comment by player-03** [comment]
How is `object.exactWidth(50)` different from `object.width = 50`? In both cases, the object's width will remain 50.

Also, pull requests are fine.

**Comment by iffy** [comment]
Oh, oops.

When I do both `object.simpleScale()` and `object.width = 100` the width ends up being not 100.  But if I omit `simpleScale()` then the width stays.  My mistake.  Sorry for the noise

**Comment by iffy** [comment]
Okay, actually `exactWidth` and `exactHeight` are different than assigning a width and height.  For instance, with this code:

```haxe
package;

import openfl.display.Sprite;
import layout.Layout;
using layout.LayoutCreator;

class Main extends Sprite {
	
	public function new () {		
		super ();

		// Components
		var box1 = new Sprite();
		box1.graphics.beginFill(0xff0000);
		box1.graphics.drawRect(0, 0, 10, 10);
		addChild(box1);

		var box2 = new Sprite();
		box2.graphics.beginFill(0x00ff00);
		box2.graphics.drawRect(0, 0, 10, 10);
		addChild(box2);	

		// Scale
		box1.simpleScale();
		box1.width = 50;
		box1.height = 100;

		box2.simpleScale();
		box2.exactWidth(50);
		box2.exactHeight(100);

		// Position
		box1.alignTopLeft();
		box2.alignTopRight();
	}
}
```

The red box is sized using assignment, the green box is sized using `exactWidth` and `exactHeight`.

When I first start the app with `openfl test neko` both boxes are the same size:

screen shot 2018-08-23 at 9 44 11 am

But if I shrink the window, the red box forgets its size while the green remembers:

screen shot 2018-08-23 at 9 44 15 am

**Comment by player-03** [comment]
Don't use `simpleScale()` for either rectangle. It'll override your assigned width and height, and it'll be overridden by `exactWidth()` and `exactHeight()`.

**Comment by iffy** [comment]
What about in the case where I want one dimension fixed and one scaled?

```haxe
		// Scale
		box1.simpleScale();
		box1.width = 50;
		box1.fillHeight();

		box2.simpleScale();
		box2.exactWidth(50);
		box2.fillHeight();
```

Initial:

screen shot 2018-08-23 at 2 55 26 pm

After resizing:

screen shot 2018-08-23 at 2 55 29 pm

**Comment by player-03** [comment]
`simpleScale()` includes both `simpleWidth()` and `simpleHeight()`, but `simpleWidth()` will override `width = 50`. Therefore, replace it with `simpleHeight()`.

Actually, `fillHeight()` will override `simpleHeight()`, so again, the real answer is just to delete the call to `simpleScale()`.

**Pull request closed without merging**
