### PR TITLE
How to use with HaxeFlixel multi-FlxState projects.

### PR DESCRIPTION
**Pull request by IBwWG**

### CODE REVIEW

**Comment by player-03** [comment]
I wrote up my own instructions last night, but it turns out I forgot to push them. Sorry about that, and thanks for taking the time to write it up.

I'm going to stick with my version, because it applies to more than just HaxeFlixel. If you see anything that could be improved, go ahead and make a new pull request.

**Comment by IBwWG** [comment]
Whoops, no worries.  I'll have a look.  Thanks for being on top of things like this :)

**Comment by IBwWG** [comment]
It looks fine the way it is, unless it matters whether `.dispose()` comes before nulling `currentLayout` when cleaning up?

**Comment by player-03** [comment]
Nope, as long as both things happen. The only problem would be if you called `dispose()` but left it as `currentLayout`. Edit: I added a check to the `dispose()` function so that that won't happen.

For the record, if you access `currentLayout` when it's null, it'll default to `stageLayout`, so there's no need to worry about null pointers.

**Pull request closed without merging**
